feat: создан проект\добавлена логика соглазно ТЗ
maloy1324/java-filmorate pull request #6
Opened 2023-12-26 17:32 UTC by maloy1324

Создан проект\добавлена логика согласно ТЗ

2023-12-26 19:51 UTC, dgumich requested changes

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserRepository.java
> +    public Collection<User> getAllUsers() {
Все таки Collection возвращают редко, стараются как минимум List.
Лучше это исправить

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserRepository.java
> +    public User getUserForId(Integer accountId) {
Правильно будет getUserById

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmRepository repository;
Надеюсь, понимаешь, какая "магия" здесь происходит=)

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmName == null || filmName.isBlank() || filmName.isEmpty()) {
Вы уже познакомились со сборщиком проектов и pom.xml.
Теперь проще добавлять библиотеки для работы.
Так вот все эти три проверки делает одна библиотека с одним методом:
https://www.baeldung.com/java-blank-empty-strings
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Лучше сделать проверку через аннотации, на самом деле это значительно проще=)

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Зачем нам логгер если мы им не пользуемся?

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exception/HandlerException.java
> +        log.error(e.getMessage());
Логгирование - важная часть, так как в логи идут в первую очередь, когда что-нибудь падает или не работает.
Поэтому необходимо подробно писать, что пошло не так, а не просто делать e.getMessage(). Как минимум надо добавить что произошла ошибка во время валидации.

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exception/HandlerException.java
> +        log.error(e.getMessage());
Здесь тоже необходимо добавить в лог понятное сообщение перед выводом ошибки.

2023-12-26 19:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Зачем логгер, если он не используется?

2023-12-27 19:05 UTC, dgumich requested changes

2023-12-27 19:05 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validator.validationRequest(film);
Из-за того, что не поставил волшебную аннотацию в контроллере, пришлось свой валидатор писать, а делать это не нужно=)

2023-12-28 13:28 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@RequestBody User user) {
Да, я сначала реализовал таким образом. Но столкнулся с проблемой, что логи записываются не так, как хотелось бы. (В сочетании с ExceptionHandler (а с ним как-то удобнее)). И чтобы исправить эту проблему решил воспользоваться своими Exception классами и валидатором. 
![image](https://github.com/maloy1324/java-filmorate/assets/110281835/3adf5a3e-ba46-4662-939d-fa0bd39fc78a)
![image](https://github.com/maloy1324/java-filmorate/assets/110281835/b5632455-e817-44e0-b371-38b44892d113)

2023-12-28 13:32 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@RequestBody User user) {
Принято, исправил

2023-12-28 13:33 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/exception/HandlerException.java
> +                .message("Ошибка: " + e.getMessage())
Это конечно не лог, а ResponseBody, в логах то нормально всё писалось, но да по разному писать смысла нет, поэтому исправил))

2023-12-28 13:36 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validator.validationRequest(film);
Ответил выше. От аннотации Valid решил отказаться в пользу удобства и контроля за Exception'ами. Свой валидатор, как мне показалось, более удачное решение. Но если не прав прошу поправить и подсказать как бы можно было это исправить (понятную запись в лог через @Valid с помощью ExceptionHandler'a)

2023-12-28 17:23 UTC, dgumich approved these changes

2023-12-28 17:23 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmRepository repository;
На все комментарии надо давать ответ=)

2023-12-28 17:23 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
И на этот комментарий тоже надо было дать ответ, что мол добавил логгирование в коде

2024-01-16 06:59 UTC, merged