feat: добавлена новая реализация согласно ТЗ ФП 10
maloy1324/java-filmorate pull request #7
Opened 2024-01-20 14:57 UTC by maloy1324

добавлена новая реализация согласно ТЗ ФП 10

2024-01-21 03:39 UTC, dgumich requested changes

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exception/HandlerException.java
> +    @ExceptionHandler
Обычно еще в скобочках указывают, какой эксепшн обрабатывает данный хендлер

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmRepositoryImpl.java
> +        return films.get(filmId).getLikes().add(userId);
Вот тут начинается самое сложное=) Надо разделять бизнес логику от слоя стореджа (то есть от хранения).
Что мы делаем в данном методе? Берем фильм, у него берем сет с лайками и добавляем лайк от пользователя. 
Где мы работаем с "бд" (с мапой)? Только здесь: films.get(filmId). Остальное - уже бизнес логика и она должна быть в сервисе. В итоге данный метод тут не нужен, можно удалить. А уже в сервисе, в методе addLike надо достать фильм по айди (для этого у нас есть метод) и сделать все тоже самое: .getLikes().add(userId);

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmRepositoryImpl.java
> +        return films.get(filmId).getLikes().remove(userId);
Аналогично, логику надо перенести в сервисный слой. Просто в сервисе достать фильм по айди и удалить у него лайк

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmRepositoryImpl.java
> +        return films.values().stream()
Когда будешь работать с реальной бд весь код заменится на поисковой запрос, так что эта логика здесь ок.

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +        users.get(userId).getFriendsId().add(friendId);
Аналогично, логика должна быть перенесена в сервисный слой. В сервисном классе получаем пользователей по айди (у нас для этого есть метод) и сетапим друг другу в друзья. В репозитории этот метод не нужен.

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +        users.get(userId).getFriendsId().remove(friendId);
Логику надо вынести в сервисный слой, а метод удалить из репозитория

2024-01-21 03:39 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +    public List<User> findCommonFriends(Long userId, Long otherId) {
Логику надо вынести в сервисный слой. Получить пользователей по айди (для этого есть метод) и сделать все то же самое (надо только поменять вызов users::get на вызов соответствующего метода у репозитория)

2024-01-21 08:41 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/exception/HandlerException.java
> +    @ExceptionHandler
Принял, видимо забыл добавить) Исправил.

2024-01-21 08:42 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmRepositoryImpl.java
> +        return films.get(filmId).getLikes().add(userId);
Буду знать, исправил)

2024-01-21 08:42 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmRepositoryImpl.java
> +        return films.get(filmId).getLikes().remove(userId);
Готово

2024-01-21 08:43 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmRepositoryImpl.java
> +        return films.values().stream()
Ну, как раз сейчас будет месяц SQL))

2024-01-21 08:43 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +        users.get(userId).getFriendsId().add(friendId);
Агась, тоже сделал

2024-01-21 08:44 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +        users.get(userId).getFriendsId().remove(friendId);
Аналогично

2024-01-21 08:44 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +    public List<User> findCommonFriends(Long userId, Long otherId) {
Иии... тоже сделано

2024-01-21 14:06 UTC, maloy1324 commented
Так же добавил аннотации @Valid в контроллерах, убрал кастомный валидатор, и настроил логирование используя MethodArgumentNotValidException (Который возникает при не успешном прохождении валидации с помощью @Valid)

2024-01-21 18:42 UTC, dgumich approved these changes

2024-01-21 18:42 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        boolean isLiked = filmRepository.getFilmById(filmId).getLikes().add(userId);
Это ок, но старайся как можно меньше делать таких операций через . 
Есть даже всякие антипатерны (цепочка вызовов) и то как должно быть правильно с точки зрения архитектуры (закон Деметры https://habr.com/ru/articles/319652/)
Тут еще ок, но не нарабатывай привычку так писать=)

2024-01-22 01:23 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        boolean isLiked = filmRepository.getFilmById(filmId).getLikes().add(userId);
Хорошо, буду знать)

2024-01-23 01:52 UTC, merged