feat: добавлена новая логика согласно ТЗ ФП 11
maloy1324/java-filmorate pull request #8
Opened 2024-02-25 07:33 UTC by maloy1324

2024-02-26 16:26 UTC, dgumich requested changes

2024-02-26 16:26 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepositoryImpl.java
> +@Qualifier("FilmDbRepositoryImpl")
@Qualifier работает не так. Её надо ставить там, где этот объект собираются внедрить, а не в его классе. Есть еще @Primary - говорит спрингу, что бин этого класса первый кандидат на внедрение. Вот она ставится над классом бина. Более подробно можешь тут почитать https://www.baeldung.com/spring-qualifier-annotation 
Если хочешь поменять название бина (а не использовать дефолтное, которое делает спринг), то его надо писать в аннотации @Repository

2024-02-26 16:26 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier("FilmDbRepositoryImpl") FilmRepository filmRepository,
Имена бинам в спринге по умолчанию даются как переменным - со строчной буквы.

2024-02-26 16:26 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserDbRepositoryImpl.java
> +@Qualifier("UserDbRepositoryImpl")
Аналогично и здесь аннотацию не надо использовать.

2024-02-27 10:43 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepositoryImpl.java
> +@Qualifier("FilmDbRepositoryImpl")
Исправил, указал название в аннотации @Repository

2024-02-27 10:43 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier("FilmDbRepositoryImpl") FilmRepository filmRepository,
Поменял. Понимаю что в таком случае используется название по умолчанию и название в аннотации @Repository можно не указывать, но для большей ясности решил оставить.

2024-02-27 10:43 UTC, maloy1324 commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserDbRepositoryImpl.java
> +@Qualifier("UserDbRepositoryImpl")
Также исправил.

2024-02-27 10:43 UTC, maloy1324 commented on src/main/resources/schema.sql
> +(
Добавил в README файл

2024-02-28 06:25 UTC, dgumich approved these changes

2024-02-28 06:25 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +        getUserById(id).getFriendsId().remove(friendId);
NPE тут будут=) Надо проверять, что пользователи не null

2024-02-28 06:25 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepositoryImpl.java
> +        if (getUserById(userId).getFriendsId().contains(friendId)) {
Очень смело без проверки пользователя на null вызывать у него что-нибудь=)

2024-03-05 15:02 UTC, merged